CREATE TABLE animals (name VARCHAR(20));
INSERT INTO animals (name) VALUES ('Dog');
INSERT INTO animals (name) VALUES ('Cat');
INSERT INTO animals (name) VALUES ('Bird');
INSERT INTO animals (name) VALUES ('Fish');
INSERT INTO animals (name) VALUES ('Rabbit');
INSERT INTO animals (name) VALUES ('Turtle');
CREATE TABLE countries (name VARCHAR(20));
INSERT INTO countries (name) VALUES ('USA');
INSERT INTO countries (name) VALUES ('Canada');
INSERT INTO countries (name) VALUES ('Germany');
INSERT INTO countries (name) VALUES ('Japan');
INSERT INTO countries (name) VALUES ('Australia');
INSERT INTO countries (name) VALUES ('Brazil');
CREATE TABLE books (title VARCHAR(50));
INSERT INTO books (title) VALUES ('Harry Potter');
INSERT INTO books (title) VALUES ('To Kill a Mockingbird');
INSERT INTO books (title) VALUES ('The Great Gatsby');
INSERT INTO books (title) VALUES ('1984');
INSERT INTO books (title) VALUES ('Pride and Prejudice');
CREATE TABLE secrets (secret VARCHAR(20));
INSERT INTO secrets (secret) VALUES ('alpha');
INSERT INTO secrets (secret) VALUES ('bravo');
INSERT INTO secrets (secret) VALUES ('charlie');
INSERT INTO secrets (secret) VALUES ('delta');
