CREATE ROLE test1 LOGIN PASSWORD 'test1-password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE test2 LOGIN PASSWORD 'test2-password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT CONNECT, CREATE ON DATABASE test TO test1, test2;
