version: "3.8"

volumes:
  postgres-data:

services:
  app:
    build: .
    environment:
      SERVER_SERVLET_CONTEXT_PATH: "/db"
      SPRING_ACTUATOR_PORT: "8082"
      BLOBSTORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://blobstorage:10000/devstoreaccount1;"
      DATABASES_CONFIG_PATH: "/app/databases_config.json"
    ports:
      - "8080:8080"
    volumes:
      - "./test/databases_config.json:/app/databases_config.json"

  blobstorage:
    image: "mcr.microsoft.com/azure-storage/azurite"
    command: "azurite-blob --blobHost 0.0.0.0"
    ports:
      - "8081:10000"

  db1:
    image: "postgres:16.2-bullseye"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "8082:5432"

  db2:
    image: "postgres:16.2-bullseye"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "8083:5432"
