name: postgres-azure-backup-test-stack
services:

  traefik:
    image: traefik:v3.6
    ports:
      - "8280:80"
      - "8281:8080"  # Traefik dashboard http://localhost:8181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./test/traefik.yaml:/etc/traefik/traefik.yaml:ro
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 2s
      retries: 5
      start_period: 2s

  client:
    image: localhost/postgres-azure-backup-client:test
    build:
      context: client
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=PathPrefix(`/`)"
      - "traefik.http.routers.client.priority=1"
      - "traefik.http.services.client.loadbalancer.server.port=8000"
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://localhost:8000/ || exit 1"
      interval: 2s
      retries: 10
      start_period: 5s
    depends_on:
      server:
        condition: service_healthy

  server:
    image: localhost/postgres-azure-backup-server:test
    build:
      context: server
    user: "${USER_ID}:${GROUP_ID}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.server.priority=2"
      - "traefik.http.services.server.loadbalancer.server.port=8080"
    environment:
      SPRING_ACTUATOR_PORT: "8282"
      SPRING_PROFILES_ACTIVE: "test"
      BLOBSTORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://blobstorage:10000/devstoreaccount1;"
      STORAGE_ACCOUNT_CONTAINER_NAME: "backups"
      DATABASES_CONFIG_PATH: /app/databases_config.json
    volumes:
      - "./test/databases_config.json:/app/databases_config.json"
      - "/tmp/test-uploads:/tmp/test-uploads"
      - "/tmp/test-documents:/tmp/test-documents"
    healthcheck:
      test: "curl --fail --silent localhost:8282/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    depends_on:
      db1:
        condition: service_healthy
      db2:
        condition: service_healthy
      blobstorage:
        condition: service_healthy

  blobstorage:
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    command: "azurite-blob --blobHost 0.0.0.0 --skipApiVersionCheck"
    ports:
      - "8081:10000"
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30

  db1:
    image: "postgres:17.5-bullseye"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "8082:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db2:
    image: "postgres:17.5-bullseye"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "8083:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
