blobstorage:
  clientId: ${AZURE_CLIENT_ID}
  tenantId: ${AZURE_TENANT_ID}
  clientSecret: ${AZURE_CLIENT_SECRET:}
  accountUrl: ${STORAGE_ACCOUNT_BLOB_URL:}
  containerName: ${STORAGE_ACCOUNT_CONTAINER_NAME:}

databasesConfigPath: ${DATABASES_CONFIG_PATH}

management:
  server:
    port: ${SPRING_ACTUATOR_PORT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
