server:
  servlet:
    context-path: /api
spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${AZURE_CLIENT_ID}

blobstorage:
  clientId: ${AZURE_CLIENT_ID}
  tenantId: ${AZURE_TENANT_ID}
  clientSecret: ${AZURE_CLIENT_SECRET:}
  accountUrl: ${STORAGE_ACCOUNT_BLOB_URL:}
  containerName: ${STORAGE_ACCOUNT_CONTAINER_NAME:}

management:
  server:
    port: ${SPRING_ACTUATOR_PORT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
