blobstorage:
  endpoint: ${BLOBSTORAGE_ENDPOINT_URL:''}
  connectionString: ${BLOBSTORAGE_CONNECTION_STRING:''}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
