databasesConfigPath: ${DATABASES_CONFIG_PATH}
spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources: []
      active-directory:
        enabled: false
      storage:
        blob:
          connection-string: ${BLOBSTORAGE_CONNECTION_STRING}
