databasesConfigPath: ${DATABASES_CONFIG_PATH}
spring:
  cloud:
    azure:
      storage:
        blob:
          connection-string: ${BLOBSTORAGE_CONNECTION_STRING}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8166/default
          audiences: mock-api-client-id

mock-oauth2-server-uri: ${MOCK_OAUTH2_SERVER_URI:}
