keyvault-endpoint: ${AZURE_KEYVAULT_ENDPOINT}
databases-config-secret-name: dbs-config

server:
  servlet:
    context-path: /api
spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: ${keyvault-endpoint}
              enabled: true

      storage:
        blob:
          container-name: ${storage-account-container-name}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${tenant-id:}/v2.0
          audiences: ${api-client-id:}

management:
  server:
    port: ${SPRING_ACTUATOR_PORT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
