name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: any
  cancel-in-progress: true

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: playwright install chromium --with-deps
      - run: docker compose up --build --wait
      - run: pytest
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
            name: test-results
            path: test-results
      - run: docker compose logs
        if: always()
  build-images:
    runs-on: ubuntu-latest
    needs: test-e2e
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"
      - run: pip install -r requirements.txt

      - run: python scripts/build_docker_image.py "${{ secrets.GITHUB_TOKEN }}" "${{ secrets.ANSIBLE_VAULT_KEY }}"
